import { displayLevel } from "../cr/levels";
import { tagSlug } from "../cr/tag";
import type { PlayerCard } from "../cr/types";
import type { BattleRecord, BattleStats } from "../repos/battles";
import type { DeckRecord } from "../repos/decks";
import type { PlayerRecord, Snapshot } from "../repos/players";
import { type Collection, type CollectionEntry, RARITY_ORDER } from "./collection";

export interface ContextInput {
  player: PlayerRecord;
  snapshot: Snapshot | null;
  stats7: BattleStats;
  stats30: BattleStats;
  recentBattles: BattleRecord[];
  collection: Collection;
  notes: string | null;
  decks: DeckRecord[];
  appUrl?: string;
  now?: Date;
}

const MAX_BATTLES = 15;
const MAX_UPGRADE_READY = 20;
const MAX_TOP_DECKS = 5;
const DECK_NOTES_CHARS = 300;

const cell = (s: string | number | null | undefined): string =>
  s === null || s === undefined || s === "" ? "-" : String(s).replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ");

// gameModeName for ranked is an internal id like "Ranked1v1_NewArena2" that an AI can't map to Path of Legend.
const modeName = (type: string, gameModeName: string): string =>
  type === "pathOfLegend" ? "Path of Legend" : gameModeName;

const gold = (n: number): string => n.toLocaleString("en-US");
const pct = (r: number): string => `${Math.round(r * 100)}%`;
const signed = (n: number): string => (n > 0 ? `+${n}` : String(n));
const utc = (iso: string): string => `${iso.slice(0, 16).replace("T", " ")} UTC`;

function table(headers: string[], rows: (string | number | null | undefined)[][]): string {
  return [
    `| ${headers.join(" | ")} |`,
    `|${headers.map(() => "---").join("|")}|`,
    ...rows.map((r) => `| ${r.map(cell).join(" | ")} |`),
  ].join("\n");
}

function ageText(fetchedAt: string, now: Date): string {
  const minutes = Math.max(0, Math.round((now.getTime() - Date.parse(fetchedAt)) / 60_000));
  if (minutes < 60) return `${minutes} min`;
  const hours = Math.round(minutes / 60);
  return hours < 48 ? `${hours} h` : `${Math.round(hours / 24)} days`;
}

function header({ player, snapshot, appUrl }: ContextInput): string {
  const lines = [
    `# Clash Royale context: ${player.name || player.tag} (${player.tag})`,
    "",
    `Synced at: ${player.lastSyncedAt ? utc(player.lastSyncedAt) : "never"}` +
      (snapshot ? ` · snapshot: ${utc(snapshot.fetchedAt)}` : ""),
  ];
  if (player.lastSyncError) lines.push(`Last sync error: ${player.lastSyncError}`);
  if (appUrl) lines.push(`App: ${appUrl.replace(/\/$/, "")}/?tag=${tagSlug(player.tag)}`);
  lines.push("Generated by the companion app; card levels are in-game display levels.");
  return lines.join("\n");
}

function profile({ snapshot }: ContextInput): string {
  if (!snapshot) return "## Profile\n\nNo snapshot yet; the player has not synced successfully.";
  const p = snapshot.player;
  const pol = p.currentPathOfLegendSeasonResult;
  const best = p.bestPathOfLegendSeasonResult;
  const polText = (r: typeof pol) =>
    r ? `league ${r.leagueNumber}, ${r.trophies} trophies${r.rank ? `, rank ${r.rank}` : ""}` : "-";
  const rows = [
    `- Exp level: ${p.expLevel}`,
    `- Trophies: ${p.trophies} (best ${p.bestTrophies})${p.arena ? ` · ${p.arena.name}` : ""}`,
    `- Path of Legend this season: ${polText(pol)}`,
    `- Best Path of Legend: ${polText(best)}`,
    `- Record: ${p.wins} W / ${p.losses} L in ${p.battleCount} battles, ${p.threeCrownWins} three-crown wins`,
    `- Clan: ${p.clan ? `${p.clan.name} (${p.clan.tag})` : "none"}`,
  ];
  if (p.currentFavouriteCard) rows.push(`- Favourite card: ${p.currentFavouriteCard.name}`);
  return `## Profile\n\n${rows.join("\n")}`;
}

function currentDeck({ snapshot, collection }: ContextInput): string {
  const deck = snapshot?.player.currentDeck ?? [];
  if (!deck.length) return "## Current deck\n\nUnknown.";
  const byId = new Map(collection.entries.map((e) => [e.id, e]));
  const rows = deck.map((c: PlayerCard) => {
    const entry = byId.get(c.id);
    const rarity = c.rarity ?? entry?.rarity;
    const evo = c.evolutionLevel ? `evo ${c.evolutionLevel}` : "";
    return [c.name, displayLevel(c.level, rarity), evo, c.elixirCost ?? entry?.elixirCost ?? null];
  });
  const costs = rows.map((r) => r[3]).filter((x): x is number => typeof x === "number");
  const avg = costs.length === deck.length ? (costs.reduce((a, b) => a + b, 0) / costs.length).toFixed(2) : "?";
  const parts = ["## Current deck", "", table(["Card", "Level", "Evolution", "Elixir"], rows), "", `Average elixir: ${avg}`];
  const tower = snapshot?.player.currentDeckSupportCards?.[0];
  if (tower) {
    const rarity = tower.rarity ?? byId.get(tower.id)?.rarity;
    parts.push(`Tower troop: ${tower.name} (level ${displayLevel(tower.level, rarity)})`);
  }
  return parts.join("\n");
}

function chests({ snapshot }: ContextInput): string {
  const items = snapshot?.chests?.items ?? [];
  if (!items.length) return "## Upcoming chests\n\nNot available.";
  return `## Upcoming chests\n\n${items.map((c) => `+${c.index}: ${c.name}`).join(", ")}`;
}

function statsLine(label: string, s: BattleStats): string {
  if (!s.total) return `- ${label}: no battles`;
  return `- ${label}: ${s.total} battles, ${s.wins}W/${s.losses}L/${s.draws}D (${pct(s.winRate)}), net trophies ${signed(s.netTrophies)}`;
}

function performance({ stats7, stats30 }: ContextInput): string {
  const parts = ["## Recent performance", "", statsLine("Last 7 days", stats7), statsLine("Last 30 days", stats30)];
  if (stats30.byMode.length) {
    parts.push(
      "",
      "By mode (30 days):",
      "",
      table(
        ["Mode", "Games", "W-L-D", "Win rate"],
        stats30.byMode.map((m) => [
          // Keep the raw name so two ranked variants stay distinguishable rows.
          m.type === "pathOfLegend" ? `Path of Legend (${m.mode})` : m.mode,
          m.games, `${m.wins}-${m.losses}-${m.draws}`, pct(m.winRate)]),
      ),
    );
  }
  if (stats30.byDeck.length) {
    parts.push(
      "",
      "Top decks (30 days):",
      "",
      table(
        ["Deck", "Games", "Win rate", "Avg elixir"],
        stats30.byDeck
          .slice(0, MAX_TOP_DECKS)
          .map((d) => [d.cards.join(", "), d.games, pct(d.winRate), d.avgElixir?.toFixed(2)]),
      ),
    );
  }
  return parts.join("\n");
}

function lastBattles({ recentBattles }: ContextInput): string {
  if (!recentBattles.length) return "## Last battles\n\nNone stored.";
  const rows = recentBattles
    .slice(0, MAX_BATTLES)
    .map((b) => [
      utc(b.battleTime).replace(" UTC", ""),
      modeName(b.type, b.gameModeName),
      b.result,
      `${b.teamCrowns}-${b.opponentCrowns}`,
      b.opponentName,
      b.teamDeck.slice(0, 8).map((c) => c.name).join(", "),
      b.opponentDeck.map((c) => c.name).join(", "),
      b.trophyChange === null ? null : signed(b.trophyChange),
    ]);
  return `## Last battles\n\nTimes in UTC, newest first.\n\n${table(
    ["Time", "Mode", "Result", "Crowns", "Opponent", "Own deck", "Opponent deck", "Trophies"],
    rows,
  )}`;
}

const evoText = (e: CollectionEntry): string =>
  e.maxEvolutionLevel ? `${e.evolutionLevel}/${e.maxEvolutionLevel}` : "";

const isMaxed = (e: CollectionEntry): boolean => e.level !== null && e.level >= e.maxLevel;

function progressText(e: CollectionEntry): string {
  if (isMaxed(e)) return "max";
  return e.countNeeded === null ? String(e.count) : `${e.count}/${e.countNeeded}`;
}

const sumGoldToMax = (entries: CollectionEntry[]): number =>
  entries.reduce((total, e) => total + (e.goldToMax ?? 0), 0);

function collectionSection({ collection, snapshot }: ContextInput): string {
  const { summary, entries } = collection;
  const deckIds = new Set((snapshot?.player.currentDeck ?? []).map((c) => c.id));
  const ownedCards = entries.filter((e) => e.owned && e.kind === "card");
  const parts = [
    "## Collection",
    "",
    `${summary.owned}/${summary.total} cards owned, ${summary.maxed} maxed, ${summary.upgradeReady} ready to upgrade. ` +
      summary.byRarity
        .map((r) => `${r.rarity} ${r.owned}/${r.total}${r.avgLevel === null ? "" : ` avg ${r.avgLevel}`}`)
        .join("; ") +
      ".",
    `Gold to max: current deck ${gold(sumGoldToMax(ownedCards.filter((e) => deckIds.has(e.id))))}, ` +
      `all owned cards ${gold(sumGoldToMax(ownedCards))}.`,
  ];
  const ready = entries.filter((e) => e.upgradeReady && e.kind === "card");
  if (ready.length) {
    parts.push(
      "",
      "Upgrade ready:",
      ...ready.slice(0, MAX_UPGRADE_READY).map((e) =>
          `- ${e.name} ${e.level} → ${e.level! + 1} (${e.count}/${e.countNeeded} cards, ${gold(e.goldNeeded ?? 0)} gold)`,
      ),
    );
    if (ready.length > MAX_UPGRADE_READY) parts.push(`- and ${ready.length - MAX_UPGRADE_READY} more`);
  }
  const rarities = [...new Set([...RARITY_ORDER, ...ownedCards.map((e) => e.rarity)])];
  for (const rarity of rarities) {
    const group = ownedCards.filter((e) => e.rarity === rarity);
    if (!group.length) continue;
    parts.push(
      "",
      `### ${rarity[0]!.toUpperCase()}${rarity.slice(1)}`,
      "",
      table(
        ["Card", "Level", "Cards", "Gold", "Evo"],
        group.map((e) => [
          e.name,
          `${e.level}/${e.maxLevel}`,
          progressText(e),
          e.goldNeeded === null ? null : gold(e.goldNeeded),
          evoText(e),
        ]),
      ),
    );
  }
  const towers = entries.filter((e) => e.owned && e.kind === "support");
  if (towers.length) {
    const tower = (e: CollectionEntry) => `${e.name} ${e.level}/${e.maxLevel}${e.upgradeReady ? " (upgrade ready)" : ""}`;
    parts.push("", `Tower troops: ${towers.map(tower).join(", ")}`);
  }
  const missing = entries.filter((e) => !e.owned && e.kind === "card");
  parts.push("", `Missing cards: ${missing.length ? missing.map((e) => e.name).join(", ") : "none"}`);
  return parts.join("\n");
}

function savedDecks({ decks }: ContextInput): string {
  if (!decks.length) return "## Saved decks\n\nNone.";
  const items = decks.map((d) => {
    const notes = d.notes.trim().replace(/\s*\n\s*/g, " ");
    const clipped = notes.length > DECK_NOTES_CHARS ? `${notes.slice(0, DECK_NOTES_CHARS)}…` : notes;
    return `- **${d.name}** (${d.source}): ${d.cards.join(", ")}${clipped ? `\n  Notes: ${clipped}` : ""}`;
  });
  return `## Saved decks\n\n${items.join("\n")}`;
}

// Quoted so headings in the user's notes can't pose as sections of this document.
const blockquote = (text: string): string =>
  text
    .split("\n")
    .map((line) => (line.trim() ? `> ${line}` : ">"))
    .join("\n");

function playerNotes({ notes }: ContextInput): string {
  const body = notes?.trim() ? `Written by the player, quoted verbatim:\n\n${blockquote(notes.trim())}` : "None yet.";
  return `## Player notes\n\n${body}`;
}

function limitations({ snapshot, now = new Date() }: ContextInput): string {
  return [
    "## Data limitations",
    "",
    "- The official API exposes no gold, gems, shop offers, or Pass Royale status; see Player notes for those.",
    "- Card levels cap at 16. Elite Wild Cards no longer exist (removed November 2025); every level costs copies plus gold.",
    "- The API battle log keeps only about 25 battles, so history covers what this app has stored since tracking began.",
    `- Snapshot age: ${snapshot ? ageText(snapshot.fetchedAt, now) : "no snapshot"}.`,
  ].join("\n");
}

/** The markdown document an AI assistant reads to advise this player. */
export function renderContextMarkdown(input: ContextInput): string {
  return `${[
    header,
    profile,
    currentDeck,
    chests,
    performance,
    lastBattles,
    collectionSection,
    savedDecks,
    playerNotes,
    limitations,
  ]
    .map((section) => section(input))
    .join("\n\n")}\n`;
}
